### ISSUE TITLE
XXE - mettre les scripts pardot

### ISSUE THREAD

**Issue by guillaumedufour** [PimTim/website-client#7]
Script de tracking type Analytics à mettre dans le footer.
`<script type="text/javascript">
piAId = '362791';
piCId = '4531';
piHostname = 'pi.pardot.com';

(function() {
                function async_load(){
                               var s = document.createElement('script'); s.type = 'text/javascript';
                               s.src = ('https:' == document.location.protocol ? 'https://pi' : 'http://cdn') + '.pardot.com/pd.js';
                               var c = document.getElementsByTagName('script')[0]; c.parentNode.insertBefore(s, c);
                }
                if(window.attachEvent) { window.attachEvent('onload', async_load); }
                else { window.addEventListener('load', async_load, false); }
})();
</script>`

Script formulaire de newsletter
`<iframe src="http://go.pardot.xxe.fr/l/361791/2017-10-18/6xjp" width="100%" height="500" type="text/html" frameborder="0" allowTransparency="true" style="border: 0"></iframe>`

Script formulaire de contact
`<iframe src="http://go.pardot.xxe.fr/l/361791/2017-10-18/6xxc" width="100%" height="500" type="text/html" frameborder="0" allowTransparency="true" style="border: 0"></iframe>`

**Comment by Pim-Bim** [comment]
On bosse plus pour XXE, je close
